("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.12") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_12.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_12.zip") ("description" . "xyzzy multiframe version") ("category") ("md5" . "be381327ee946f12ff37929124897138") ("time" . 3555910582) ("depends") ("changes" . "") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
