("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.9.1") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_9_alpha2.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_9_alpha2.zip") ("description" . "0.2.3.9 alpha2 version.") ("category") ("md5" . "d01faf71670e70c7979328fe4d55099b") ("time" . 3547415978) ("depends") ("changes" . "0.2.3.9 alpha2 version.") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
