("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.11") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_11.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_11.zip") ("description" . "xyzzy multiframe version") ("category") ("md5" . "d308a8d8fa5d99b471f32cb664324c76") ("time" . 3553769981) ("depends") ("changes" . "") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
