("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.9.2") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_9_RC1.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_9_RC1.zip") ("description" . "0.2.3.9 RC1") ("category") ("md5" . "8a8cf4f76f5ff049597a258ae5eb3cc3") ("time" . 3548418447) ("depends") ("changes" . "0.2.3.9 RC1.") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
