("name" . "Xyzzy Multiframe Version")
("author" . "mumurik765")
("url" . "https://raw.github.com/mumurik/xyzzy/tree/ni-integrate/latest-xyzzy-info.l")
("description" . "Xyzzyのマルチフレーム版配布サイトです。")
("packages"
 (("name" . "xyzzy") ("version" . "0.2.3.10") ("author" . "mumurik765") ("file" . "multiframe_0_2_3_10_RC1.zip") ("src" . "https://bitbucket.org/mumurik/xyzzy/downloads/multiframe_0_2_3_10_RC1.zip") ("description" . "0.2.3.10 RC1") ("category") ("md5" . "1b6b0a56ebd67faae879de37242786ab") ("time" . 3550828362) ("depends") ("changes" . "0.2.3.10 RC1.") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
 )
